### ISSUE TITLE
Downloaded files cached by proxies

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-log-spooler#3]
When using a proxy, cache, CDN, or load balancer such as Cloudflare , files which would otherwise by password protected are cached and can therefore be accessed without credentials so long as the cached version exists.

Cache control headers must be sent when delivering a protected file. 

`Cache-Control "private"`

**Comment by richplane** [comment]
Hmm I had "Pragma: no-cache". Changed as you suggested.
